mode = "fancy"

[light_sources]
water_sensitive_check = true
block_entities = true
entities = true
tnt = "simple"
creeper = "simple"

[light_sources.settings]

[light_sources.settings.block_entities]

[light_sources.settings.block_entities.minecraft]
bed = true
furnace = true
dropper = true
daylight_detector = true
sign = true
jukebox = true
brewing_stand = true
sculk_sensor = true
conduit = true
beehive = true
dispenser = true
smoker = true
lectern = true
skull = true
campfire = true
barrel = true
chest = true
piston = true
end_portal = true
shulker_box = true
enchanting_table = true
banner = true
structure_block = true
ender_chest = true
bell = true
end_gateway = true
comparator = true
beacon = true
command_block = true
jigsaw = true
hopper = true
mob_spawner = true
trapped_chest = true
blast_furnace = true

[light_sources.settings.entities]

[light_sources.settings.entities.minecraft]
zombie_horse = true
axolotl = true
egg = true
zoglin = true
spawner_minecart = true
llama = true
mule = true
bat = true
husk = true
experience_bottle = true
rabbit = true
firework_rocket = true
silverfish = true
giant = true
drowned = true
item = true
goat = true
horse = true
vindicator = true
minecart = true
spectral_arrow = true
llama_spit = true
mooshroom = true
glow_item_frame = false
tnt = true
snowball = true
parrot = true
creeper = true
lightning_bolt = true
ravager = true
evoker_fangs = true
chest_minecart = true
tropical_fish = true
slime = true
pillager = true
area_effect_cloud = true
blaze = true
piglin = true
end_crystal = true
endermite = true
ender_pearl = true
zombie = true
guardian = true
fireball = true
illusioner = true
eye_of_ender = true
wither_skull = true
wolf = true
tnt_minecart = true
zombie_villager = true
elder_guardian = true
boat = true
small_fireball = true
strider = true
cave_spider = true
cod = true
snow_golem = true
witch = true
spider = true
command_block_minecart = true
panda = true
bee = true
arrow = true
cow = true
magma_cube = true
pig = true
skeleton = true
hoglin = true
armor_stand = true
experience_orb = true
dolphin = true
stray = true
shulker = true
turtle = true
salmon = true
vex = true
wandering_trader = true
wither_skeleton = true
piglin_brute = true
ocelot = true
furnace_minecart = true
item_frame = true
phantom = true
ender_dragon = true
leash_knot = true
evoker = true
marker = true
glow_squid = true
shulker_bullet = true
squid = true
enderman = true
dragon_fireball = true
chicken = true
trader_llama = true
donkey = true
fox = true
iron_golem = true
zombified_piglin = true
cat = true
ghast = true
sheep = true
player = true
pufferfish = true
potion = true
trident = true
villager = true
skeleton_horse = true
fishing_bobber = true
polar_bear = true
hopper_minecart = true
falling_block = true
painting = true
wither = true
