[versions]
minecraft = "1.20.1"
quilt_mappings = "1.20.1+build.23"
quilt_loader = "0.19.5"

quilted_fabric_api = "7.1.2+0.87.0-1.20.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.2.+" }
quilt_flower = { id = "io.github.juuxel.loom-quiltflower", version = "1.8.+" }